export const cell: string;
export const startButton: string;
export const container: string;
export const players: string;
export const player1: string;
export const player2: string;
export const title: string;
export const info: string;
export const hoverTitle: string;
